kind: Secret
apiVersion: v1
metadata:
  name: pyfastapi-hello-app
  labels:
    app: pyfastapi-hello-app
    app.kubernetes.io/name: pyfastapi-hello-app
    app.kubernetes.io/part-of: python-apps
    app.openshift.io/runtime: python
data:
  APP_TITLE: ZGVtbw==
type: Opaque